### ISSUE TITLE
Error installing 0.0.7 on Windows

### ISSUE THREAD

**Issue by magiclevinho** [rozzac90/pinnacle#15]
Dear @rozzac90 !
I have trouble again with installing pinnacle 0.0.7 version on Windows 10 again.

```
C:\Users\Administrator>python --version
Python 2.7.15

C:\Users\Administrator>pip install pinnacle
Collecting pinnacle
  Using cached https://files.pythonhosted.org/packages/12/06/55706032d6d245e1f28b7e3c3c1ab48ec978ee5a3de260adb0a91ea36a72/pinnacle-0.0.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini~1\appdata\local\temp\2\pip-install-cqitoa\pinnacle\setup.py", line 3, in <module>
        from pinnacle import __version__
      File "pinnacle\__init__.py", line 1, in <module>
        from pinnacle.apiclient import APIClient
      File "pinnacle\apiclient.py", line 1, in <module>
        from pinnacle.baseclient import BaseClient
      File "pinnacle\baseclient.py", line 3, in <module>
        import requests
    ImportError: No module named requests

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admini~1\appdata\local\temp\2\pip-install-cqitoa\pinnacle\

C:\Users\Administrator>python -m pip --version
pip 18.0 from C:\Python27\lib\site-packages\pip (python 2.7)
```

Can you help me out?

**Comment by magiclevinho** [comment]
OK, somehow I figured out.
### You have to install manually "requests" package:
**pip install requests**
Maybe this package isn't named in the installer.

**Comment by liampauling** [comment]
Its due to setup importing the version, here is a fix:

```python
with open('pinnacle/__init__.py', 'r') as f:
    version = re.search(
        r'^__version__\s*=\s*[\'"]([^\'"]*)[\'"]',
        f.read(),
        re.MULTILINE
    ).group(1)
```
