### ISSUE TITLE
Error installing pinnacle-0.0.5 and pinnacle-0.0.4 on windows

### ISSUE THREAD

**Issue by Mangiafuoco** [rozzac90/pinnacle#3]
```
d:\Pinnacle>pip install pinnacle
Collecting pinnacle
  Using cached pinnacle-0.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\sas\appdata\local\temp\pip-build-gbe0wo\pinnacle\setup.py", line 3, in <module>
        from pinnacle import __version__
      File "pinnacle\__init__.py", line 1, in <module>
        from pinnacle.apiclient import APIClient
      File "pinnacle\apiclient.py", line 2, in <module>
        from pinnacle import endpoints
      File "pinnacle\endpoints\__init__.py", line 3, in <module>
        from pinnacle.endpoints.betting import Betting
      File "pinnacle\endpoints\betting.py", line 11, in <module>
        class Betting(BaseEndpoint):
      File "pinnacle\endpoints\betting.py", line 36, in Betting
        alt_line_id=None, win_risk_stake=WinRiskType.Risk.value, accept_better_line=Boolean.TRUE.value,
    AttributeError: 'str' object has no attribute 'value'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\sas\appdata\local\temp\pip-build-gbe0wo\pinnacle\
```

**Comment by rozzac90** [comment]
I can't reproduce this error on mac or windows from clean pip installs of the package, any further info?
